### ISSUE TITLE
Utilizar o firebase (sugestão)

### ISSUE THREAD

**Issue by heliandro** [iuriian/lista-de-tarefas#2]
Utilizar o firebase no plano free.
Você pode fazer as operações diretamente no firebase/firestore, sem precisar usar as cloud functions.
ver os exemplos web da documentação do firestore: https://firebase.google.com/docs/firestore/quickstart?hl=pt-br.

**Comment by iuriian** [comment]
Boa sugestão, consegui avançar graças ao firestore, obrigado.

**Comment by heliandro** [comment]
tudo certo. Gostei.
